import Link from "next/link";
import { notFound } from "next/navigation";
import { getServices } from "@/backend/supabase/services";
import { AddToCartButton } from "@/frontend/components/service-cart";
export const dynamic = "force-dynamic";
export const revalidate = 0;
const data: Record<string,{title:string; intro:string; benefits:string[]; deliverables:string[]}> = {
 "web-development":{title:"Web Development",intro:"Digital experiences that make your offer easier to understand, trust, and choose.",benefits:["A clear path from first visit to action","Fast pages that respect attention","A codebase your team can extend"],deliverables:["Discovery and information architecture","Responsive interface implementation","CMS or content model","Analytics-ready launch"]},
 "mobile-app-development":{title:"Mobile App Development",intro:"Mobile products that feel natural to use and practical to maintain.",benefits:["Choose native or cross-platform with evidence","Design for the moments that matter","A launch plan beyond the app store"],deliverables:["User flows and prototypes","iOS and Android implementation","App analytics setup","Release and handover support"]},
 "ai-ml-solutions":{title:"AI / ML Solutions",intro:"Practical AI for the work that takes too long, gets repeated, or needs a better signal.",benefits:["Start with a measurable use case","Keep data privacy in the design","Test accuracy before scale"],deliverables:["Use-case and data audit","Document processing or assistant workflow","Evaluation criteria and test set","Human-in-the-loop controls"]},
 "cloud-devops":{title:"Cloud & DevOps",intro:"Infrastructure and delivery systems that help your team ship with confidence.",benefits:["Shorter, safer release cycles","Visibility when something changes","Cost and security considered together"],deliverables:["Cloud architecture review","CI/CD pipeline","Monitoring and alerting","Runbooks and team handover"]},
 "ui-ux-design":{title:"UI / UX Design",intro:"Interfaces that turn complex decisions into clear next steps.",benefits:["Research before decoration","Prototypes that answer questions early","A system that keeps quality consistent"],deliverables:["Research plan and user flows","Wireframes and clickable prototype","Visual direction and design system","Usability test findings"]},
 "it-consulting-support":{title:"IT Consulting & Support",intro:"A calm, experienced second brain for your technology decisions and day-to-day reality.",benefits:["A sharper view of technical trade-offs","A prioritised plan, not a long wish list","Support that fits your internal team"],deliverables:["Technical audit or architecture review","Roadmap and risk register","Maintenance and support plan","Documentation your team can use"]}
};
export async function generateStaticParams(){return (await getServices()).map(item=>({slug:item.slug}))}
export default async function Service({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const services=await getServices();const catalogService=services.find(item=>item.slug===slug);const service=data[slug] ?? (catalogService ? { title:catalogService.name, intro:catalogService.description, benefits:catalogService.included.slice(0, 3), deliverables:catalogService.included } : undefined);if(!service)notFound();const relatedServices=catalogService ? services.filter(item=>item.category===catalogService.category&&item.slug!==catalogService.slug).slice(0,3) : [];return <><section className="page-hero"><div className="container service-detail-hero"><div className="eyebrow"><Link href="/services">Services</Link> / {service.title}</div><h1>{service.title}</h1><p className="lead">{service.intro}</p>{catalogService && <div className="service-detail-price"><strong>{catalogService.price ? `From ₹${catalogService.price.toLocaleString("en-IN")}` : "Custom quote"}</strong><span>⏱ {catalogService.delivery}</span></div>}<div className="hero-actions">{catalogService && <AddToCartButton service={catalogService} />}<Link className="btn btn-ghost" href="/cart#quote">Request a quote</Link></div></div></section><section className="section"><div className="container detail-grid"><div><div className="eyebrow">What changes</div><h2>Useful from the first release.</h2><div className="list">{service.benefits.map((x,i)=><div className="list-item" key={x}><strong>0{i+1}</strong><p>{x}</p></div>)}</div></div><div><div className="eyebrow">What you receive</div><h2>Concrete deliverables.</h2><div className="list">{service.deliverables.map(x=><div className="list-item" key={x}><strong>✓</strong><p>{x}</p></div>)}</div>{catalogService && <><div className="eyebrow detail-tech-eyebrow">Technologies</div><p>{catalogService.technologies.join(" · ")}</p></>}</div></div></section>{relatedServices.length > 0 && <section className="section related-services"><div className="container"><div className="section-head"><div><div className="eyebrow">Build the full solution</div><h2>Related {catalogService?.category} services.</h2></div><Link className="card-link" href="/services">Browse all services</Link></div><div className="service-grid">{relatedServices.map(item=><article className="service-card" key={item.slug}><div className="eyebrow">{item.category}</div><h3>{item.name}</h3><p>{item.description}</p><Link className="card-link" href={`/services/${item.slug}`}>View details →</Link></article>)}</div></div></section>}<section className="cta"><div className="container cta-row"><div><div className="eyebrow">Ready when you are</div><h2>Let’s talk about {service.title.toLowerCase()}.</h2></div><Link className="btn btn-primary" href="/cart#quote">Build your project package</Link></div></section></>}
