import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About TechJest and Our Founders",
  description: "Learn about TechJest, founded by Chayan Khatua and Amit Singh Panwar, and our practical approach to building useful software.",
  alternates: { canonical: "/about" },
};

export default function About(){return <><section className="page-hero"><div className="container"><div className="eyebrow">About TechJest</div><h1>Good technology should make work feel lighter.</h1><p className="lead">We started TechJest to give ambitious teams a practical alternative to slow handoffs and vague technical promises.</p></div></section><section className="section"><div className="container detail-grid"><div><div className="eyebrow">Our founders</div><h2>Built by Chayan Khatua and Amit Singh Panwar.</h2></div><div><p className="lead">TechJest was founded by Chayan Khatua and Amit Singh Panwar to help teams turn strong ideas into useful, dependable digital products.</p><p className="lead">We work with people who know their customers and need a technical partner to move from intention to execution. That means asking better questions, keeping scope honest, and making the work visible.</p></div></div></section><section className="section band"><div className="container"><div className="eyebrow">How we work</div><h2>Values with a behavior attached.</h2><div className="process-grid"><div className="process-step"><h3>Clarity</h3><p>We write down the decision, the trade-off, and the next step.</p></div><div className="process-step"><h3>Useful over impressive</h3><p>We measure progress by what users can do, not by how complex the system sounds.</p></div><div className="process-step"><h3>Ownership</h3><p>You receive the knowledge, files, and code needed to keep moving.</p></div><div className="process-step"><h3>Care</h3><p>We test the edges, communicate early, and leave things better documented.</p></div></div></div></section></>}
